name: forestay-serial
version: '0.1.0.0'
synopsis: A combination of multiple serialisation formats
description: Please see README.md
category: Prelude
author: David Baynard
maintainer: davidbaynard@gmail.com
copyright: 2016 David Baynard
license: Apache
github: dbaynard/haskell
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Forestay.Serial
  dependencies:
  - base >=4.9 && <5
  - forestay-data
  - aeson >= 1.0.0.0
  - binary
  - cereal
  - data-msgpack
  - lens-aeson
  - protobuf
  - unordered-containers
  - yaml
tests:
  forestay-data-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hspec
    - forestay-serial
