name: forestay
version: '0.1.0.0'
synopsis: A prelude alternative based on lifted-protolude
description: Please see README.md
category: Prelude
author: David Baynard
maintainer: davidbaynard@gmail.com
copyright: 2016 David Baynard
license: Apache
github: dbaynard/haskell
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Forestay
  - Forestay.Containers
  - Forestay.Lens
  #reexported-modules:
  #- Protolude.Lifted
  #- Unsafe
  #- Control.Monad.Ether.Implicit
  #- Data.Array.Lens
  #- Data.HashSet.Lens
  #- Data.IntSet.Lens
  #- Data.List.Lens
  #- Data.Map.Lens
  #- Data.Sequence.Lens
  #- Data.Set.Lens
  #- Data.Tree.Lens
  #- Data.Vector.Lens
  #- Data.Vector.Lens
  dependencies:
  - base >=4.9 && <5
  - containers
  - ether
  - hashable
  - hashable-time
  - lens
  - lens-datetime
  - lifted-protolude
  - tagged
  - time
  - unordered-containers
  - vector
tests:
  forestay-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hspec
    - forestay
