name: forestay-data
version: '0.1.0.0'
synopsis: A prelude based on lifted-protolude for defining data types
description: Please see README.md
category: Prelude
author: David Baynard
maintainer: davidbaynard@gmail.com
copyright: 2016 David Baynard
license: Apache
github: dbaynard/haskell
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Forestay.Data
  - Forestay.Deriving.Monoid
  - Forestay.Lens.Definition
  - Forestay.Pretty
  dependencies:
  - base >=4.9 && <5
  - base16-bytestring
  - base64-bytestring
  - dlist
  - hashable
  - hashable-time
  - lifted-protolude
  - profunctors
  - tagged
  - time
  - safe
  - vector
  - wl-pprint-text
tests:
  forestay-data-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hspec
    - forestay-data
